version: 0.1
input:
  strava:
    athlete--activities:
      id: id
      moving_time: 'moving_time_seconds'
      distance: 'distance'
      name: 'name'
      total_elevation_gain: 'elevation'
      start_latlng[1]: 'lat'
      start_latlng[2]: 'long'
      average_speed: 'average_speed'
      max_speed: 'max_speed'
      average_watts: 'average_watts'
      sport_type: 'sport_type'
      start_date: 'start_date'
    activities:
      id: activity_id
      description: description
      calories: calories
      gear.name: gear_name
output:
  obsidian:
    - strategy: 'logs'
      data:
        title_template: "Strava - {{sport_type}}"
        body_template: "\n**{{name}}** {{description__LINKED}}\n"
        log_datetime: "start_date"
        source: "Strava"
        metadata:
          - distance
          - elevation
          - lat
          - long
          - average_speed
          - max_speed
          - average_watts
          - gear_name
          - moving_time
          - calories__LINKED
          - gear_name__LINKED
pipeline:
  - field: 'sport_type'
    transform:
      - 'camelCaseToSpaces'
  - field: 'moving_time_seconds'
    transform:
      - 'secondsToTimeString'
    toField: 'moving_time'
  - field: 'distance'
    transform:
      - 'metersToMiles'
  - field: 'elevation'
    transform:
      - 'metersToFeet'
  - field: 'average_speed'
    transform:
      - 'metersPerSecondToMph'
  - field: 'max_speed'
    transform:
      - 'metersPerSecondToMph'
  - field: 'id'
    linkTo: 'activity_id'